hosts:
  - "localhost"

loglevel: 5

listen:
  -
    port: 5222
    module: ejabberd_c2s
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: local
    starttls: false  

acl:
  local:
    user_regexp: ""

access_rules:
  local:
    allow: all
  c2s:
    deny: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  register:
    deny: all

shaper:
  normal: 1000
  fast: 50000

default_db: sql 

sql_type: pgsql 
# FIX: Changed to PostgreSQL service name
sql_server: postgres-db
sql_port: 5432 
sql_database: ejabberd_db
sql_username: ejabberd_user 
sql_password: "1110ya" 
sql_pool_size: 10 

update_sql_schema: true

shaper_rules:
  max_user_sessions: 10
  max_user_offline_messages:
    - 5000
    - 1h
  c2s_shaper:
    - fast
  s2s_shaper:
    - fast

auth_method: [external]
extauth_program: "/home/ejabberd/check_pass_null.pl"
auth_use_cache: false

modules:
  mod_mam:
    db_type: sql
    default: always
    assume_mam_usage: true
    cache_life_time: 86400 
    use_cache: true

  mod_offline:
    db_type: sql
    access_max_user_messages: max_user_offline_messages

  mod_admin_extra: {}
  mod_roster: {}
  mod_vcard: {}
  mod_disco: {}
  mod_adhoc: {}